# Generated by Django 5.2.1 on 2025-05-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
